export const nzCitiesData = [
  { value: "auckland", label: "Auckland" },
  { value: "blenheim", label: "Blenheim" },
  { value: "cambridge", label: "Cambridge" },
  { value: "christchurch", label: "Christchurch" },
  { value: "dunedin", label: "Dunedin" },
  { value: "gisborne", label: "Gisborne" },
  { value: "hamilton", label: "Hamilton" },
  { value: "hastings", label: "Hastings" },
  { value: "huntly", label: "Huntly" },
  { value: "invercargill", label: "Invercargill" },
  { value: "kapiti", label: "Kapiti" },
  { value: "kerikeri", label: "Kerikeri" },
  { value: "matamata", label: "Matamata" },
  { value: "morrinsville", label: "Morrinsville" },
  { value: "napier", label: "Napier" },
  { value: "nelson", label: "Nelson" },
  { value: "new_plymouth", label: "New Plymouth" },
  { value: "palmerston_north", label: "Palmerston North" },
  { value: "queenstown", label: "Queenstown" },
  { value: "rotorua", label: "Rotorua" },
  { value: "taupo", label: "Taupō" },
  { value: "tauranga", label: "Tauranga" },
  { value: "thames", label: "Thames" },
  { value: "wellington", label: "Wellington" },
  { value: "whakatane", label: "Whakatāne" },
  { value: "whangarei", label: "Whangārei" },
];
